name: Publish Python Package

on:
  release:
    types: [created]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine python-dotenv

      - name: Load environment variables from .env
        run: |
          export $(grep -v '^#' .env | xargs)  # This loads variables from .env

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: $TWINE_USERNAME
          TWINE_PASSWORD: $TWINE_PASSWORD
        run: twine upload dist/*
